version: '3'

services:
  nginx:
    ports:
      - "8008:80"
      - "8443:443"
    volumes:
      - ./nginx/local/default.conf:/etc/nginx/conf.d/www.conf
      - ../logs/nginx:/var/log/nginx
      - ../src:/var/www/html

  php:
    volumes:
      - ./php/local/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/local/php.ini:/usr/local/etc/php/php.ini
      - ../logs/php:/var/log/php
      - ../src:/var/www/html
    ports:
      - "9000:9000"